project_id = "ppnapggjcpnhoqbnbucw"

[functions.extract-requirements]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.generate-katalon]
verify_jwt = false

[functions.validate-katalon]
verify_jwt = false

[functions.analyze-figma]
verify_jwt = false

[functions.enhance-test-cases]
verify_jwt = false

[functions.ingest-source-code]
verify_jwt = false

[functions.trigger-katalon-run]
verify_jwt = false

[functions.receive-test-results]
verify_jwt = false

[functions.map-code-requirements]
verify_jwt = false
