import { useState } from "react";
import { motion } from "framer-motion";
import { Download, FileCode, Check, Loader2, Edit3, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { apiClient } from "@/lib/apiClient";
import JSZip from "jszip";
import { saveAs } from "file-saver";

interface KatalonFile {
  file_path: string;
  content: string;
}

interface KatalonScript extends KatalonFile {
  test_case_code: string;
}

interface KatalonOutput {
  scripts: KatalonScript[];
  page_objects: KatalonFile[];
  test_suite: KatalonFile;
}

const KatalonExport = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [katalon, setKatalon] = useState<KatalonOutput | null>(null);
  const [editingIdx, setEditingIdx] = useState<number | null>(null);
  const [editContent, setEditContent] = useState("");
  const [editType, setEditType] = useState<"script" | "pageObject" | "suite">("script");

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await apiClient.post<any>("/pipelines/automation", { project_id: "" }); // Adjust if project context needed
      if (response.error) throw new Error(response.error);
      setKatalon(response.katalon);
      toast.success("Katalon scripts generated! Review and refine before downloading.");
    } catch (err: any) {
      console.error(err);
      toast.error(err.message || "Failed to generate Katalon scripts");
    }
    setIsGenerating(false);
  };

  const startEditScript = (idx: number) => {
    if (!katalon) return;
    setEditingIdx(idx);
    setEditType("script");
    setEditContent(katalon.scripts[idx].content);
  };

  const startEditPageObject = (idx: number) => {
    if (!katalon) return;
    setEditingIdx(idx);
    setEditType("pageObject");
    setEditContent(katalon.page_objects[idx].content);
  };

  const startEditSuite = () => {
    if (!katalon) return;
    setEditingIdx(0);
    setEditType("suite");
    setEditContent(katalon.test_suite.content);
  };

  const saveEditedContent = () => {
    if (!katalon || editingIdx === null) return;
    const updated = { ...katalon };
    if (editType === "script") {
      updated.scripts = [...updated.scripts];
      updated.scripts[editingIdx] = { ...updated.scripts[editingIdx], content: editContent };
    } else if (editType === "pageObject") {
      updated.page_objects = [...updated.page_objects];
      updated.page_objects[editingIdx] = { ...updated.page_objects[editingIdx], content: editContent };
    } else {
      updated.test_suite = { ...updated.test_suite, content: editContent };
    }
    setKatalon(updated);
    setEditingIdx(null);
    toast.success("Script updated");
  };

  const handleDownloadZip = async () => {
    if (!katalon) return;
    const zip = new JSZip();

    katalon.scripts.forEach((s) => zip.file(s.file_path, s.content));
    katalon.page_objects.forEach((p) => zip.file(p.file_path, p.content));
    zip.file(katalon.test_suite.file_path, katalon.test_suite.content);

    // Add a readme
    zip.file("README.md", `# SimplifyTesting — Katalon Automation Package\n\nGenerated by SimplifyTesting AI Test Engineering Platform.\n\n## Structure\n- Scripts/ — Test case Groovy scripts\n- Object Repository/ — Page object definitions\n- Test Suites/ — Test suite configurations\n\n## Usage\n1. Open Katalon Studio\n2. Import this project\n3. Run the test suite\n`);

    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, "katalon-automation-package.zip");
    toast.success("ZIP package downloaded!");
  };

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-3xl font-bold text-foreground tracking-tight">Katalon Automation</h1>
        <p className="text-muted-foreground mt-2">
          Generate → Refine → Download automation scripts as a ZIP package
        </p>
      </motion.div>

      {/* Step 1: Generate */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
        className="mt-8 p-6 rounded-xl bg-card border border-border"
      >
        <div className="flex items-center gap-3 mb-3">
          <div className="w-7 h-7 rounded-full bg-primary/20 text-primary flex items-center justify-center text-xs font-bold">1</div>
          <h3 className="text-sm font-semibold text-foreground">AI Script Generation</h3>
        </div>
        <p className="text-xs text-muted-foreground mb-4">Generate Katalon Groovy scripts from approved/refined test cases</p>
        <Button onClick={handleGenerate} disabled={isGenerating} size="sm" className="gap-2">
          {isGenerating && <Loader2 className="w-4 h-4 animate-spin" />}
          <FileCode className="w-4 h-4" />
          {isGenerating ? "Generating..." : katalon ? "Regenerate" : "Generate Scripts"}
        </Button>
      </motion.div>

      {/* Step 2: Refine */}
      {katalon && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="mt-4 p-6 rounded-xl bg-card border border-border"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="w-7 h-7 rounded-full bg-warning/20 text-warning flex items-center justify-center text-xs font-bold">2</div>
            <h3 className="text-sm font-semibold text-foreground">Human Refinement</h3>
            <span className="text-xs text-muted-foreground ml-auto">Click edit to refine any script</span>
          </div>

          {/* Scripts */}
          <div className="space-y-3">
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Test Scripts</h4>
            {katalon.scripts.map((script, i) => (
              <div key={i} className="rounded-lg bg-surface border border-border overflow-hidden">
                <div className="flex items-center justify-between px-4 py-2 bg-muted">
                  <span className="text-xs font-mono text-muted-foreground">{script.file_path}</span>
                  <button onClick={() => startEditScript(i)} className="p-1 rounded hover:bg-background text-muted-foreground hover:text-foreground transition-colors">
                    <Edit3 className="w-3.5 h-3.5" />
                  </button>
                </div>
                {editingIdx === i && editType === "script" ? (
                  <div className="p-3 space-y-2">
                    <Textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={12} className="text-xs font-mono" />
                    <div className="flex gap-2">
                      <Button size="sm" onClick={saveEditedContent} className="gap-1"><Save className="w-3 h-3" /> Save</Button>
                      <Button size="sm" variant="outline" onClick={() => setEditingIdx(null)}>Cancel</Button>
                    </div>
                  </div>
                ) : (
                  <pre className="p-4 text-xs font-mono text-foreground/80 overflow-x-auto max-h-40">{script.content}</pre>
                )}
              </div>
            ))}

            {/* Page Objects */}
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mt-4">Page Objects</h4>
            {katalon.page_objects.map((po, i) => (
              <div key={i} className="rounded-lg bg-surface border border-border overflow-hidden">
                <div className="flex items-center justify-between px-4 py-2 bg-muted">
                  <span className="text-xs font-mono text-muted-foreground">{po.file_path}</span>
                  <button onClick={() => startEditPageObject(i)} className="p-1 rounded hover:bg-background text-muted-foreground hover:text-foreground transition-colors">
                    <Edit3 className="w-3.5 h-3.5" />
                  </button>
                </div>
                {editingIdx === i && editType === "pageObject" ? (
                  <div className="p-3 space-y-2">
                    <Textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={8} className="text-xs font-mono" />
                    <div className="flex gap-2">
                      <Button size="sm" onClick={saveEditedContent} className="gap-1"><Save className="w-3 h-3" /> Save</Button>
                      <Button size="sm" variant="outline" onClick={() => setEditingIdx(null)}>Cancel</Button>
                    </div>
                  </div>
                ) : (
                  <pre className="p-4 text-xs font-mono text-foreground/80 overflow-x-auto max-h-32">{po.content}</pre>
                )}
              </div>
            ))}

            {/* Test Suite */}
            <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mt-4">Test Suite</h4>
            <div className="rounded-lg bg-surface border border-border overflow-hidden">
              <div className="flex items-center justify-between px-4 py-2 bg-muted">
                <span className="text-xs font-mono text-muted-foreground">{katalon.test_suite.file_path}</span>
                <button onClick={startEditSuite} className="p-1 rounded hover:bg-background text-muted-foreground hover:text-foreground transition-colors">
                  <Edit3 className="w-3.5 h-3.5" />
                </button>
              </div>
              {editingIdx === 0 && editType === "suite" ? (
                <div className="p-3 space-y-2">
                  <Textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} rows={6} className="text-xs font-mono" />
                  <div className="flex gap-2">
                    <Button size="sm" onClick={saveEditedContent} className="gap-1"><Save className="w-3 h-3" /> Save</Button>
                    <Button size="sm" variant="outline" onClick={() => setEditingIdx(null)}>Cancel</Button>
                  </div>
                </div>
              ) : (
                <pre className="p-4 text-xs font-mono text-foreground/80 overflow-x-auto max-h-32">{katalon.test_suite.content}</pre>
              )}
            </div>
          </div>
        </motion.div>
      )}

      {/* Step 3: Download ZIP */}
      {katalon && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
          className="mt-4 p-6 rounded-xl bg-card border border-success/30"
        >
          <div className="flex items-center gap-3 mb-3">
            <div className="w-7 h-7 rounded-full bg-success/20 text-success flex items-center justify-center text-xs font-bold">3</div>
            <h3 className="text-sm font-semibold text-foreground">Download Final Package</h3>
          </div>
          <p className="text-xs text-muted-foreground mb-4">
            Download the complete Katalon project as a ZIP file. Includes {katalon.scripts.length} scripts, {katalon.page_objects.length} page objects, and 1 test suite.
          </p>
          <Button onClick={handleDownloadZip} size="sm" className="gap-2">
            <Download className="w-4 h-4" /> Download ZIP Package
          </Button>
        </motion.div>
      )}
    </div>
  );
};

export default KatalonExport;
